name = "GatherShot"
uuid = "fc9c1619-52aa-4158-aff4-9a877b4db880"
authors = ["adolgert <adolgert@uw.edu>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
